SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

CREATE TABLE IF NOT EXISTS `LivingRoom` (
  `id` int(2) NOT NULL AUTO_INCREMENT,
  `variety` varchar(50) NOT NULL DEFAULT '',
  `name` varchar(50) NOT NULL DEFAULT '',
  `filepath` varchar(100) NOT NULL,
  `price` varchar(50) NOT NULL DEFAULT '',
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=36 ;

INSERT INTO `LivingRoom` (`id`, `variety`, `name`, `filepath`, `price`) VALUES
(1, 'Sofa', 'Blue Sofa', 'livingRoom/blueSofa.jpg', '£400.00'),
(2, 'Sofa', 'Grey Sofa', 'livingRoom/greySofa.jpg', '£350.00'),
(3, 'Sofa', 'Red Sofa', 'livingRoom/redSofa.png', '£400.00'),
(4, 'Sofa', 'Yellow Sofa', 'livingRoom/yellowSofa.jpg', '£3050.00'),
(5, 'Sofa', 'Green Sofa', 'livingRoom/greenSofa.jpg', '£400.00'),
(6, 'Sofa', 'Orange Sofa', 'livingRoom/orangeSofa.jpg', '£3500.00'),
(7, 'Sofa', 'Leather Sofa', 'livingRoom/pinkSofa.jpg', '£400.00'),
(8, 'Sofa', 'Pink Sofa', 'livingRoom/pinkSofa.jpg', '£3050.00'),
(9, 'Sofa', 'Sofa Bed', 'livingRoom/sofaBed.jpg', '£400.00'),
(10, 'Sofa', 'L-Sofa', 'livingRoom/lSofa.jpg', '£3050.00'),
(11, 'Coffee Table', 'Glass Coffee Table', 'livingRoom/glassCoffeeTable.jpg', '£40.00'),
(12, 'Coffee Table', 'Industrial Coffee Table', 'livingRoom/industrialCoffeeTable.jpg', '£50.00'),
(13, 'Coffee Table', 'Wooden Coffee Table', 'livingRoom/woodenCoffeeTable.jpg', '£80.00'),
(14, 'Coffee Table', 'Circular Coffee Table', 'livingRoom/circularCoffeeTable.jpg', '£150.00'),
(15, 'Coffee Table', 'Thin Coffee Table', 'livingRoom/thinCoffeeTable.jpg', '£140.00'),
(16, 'Rug', 'Rug 1', 'livingRoom/rug1.jpg', '£50.00'),
(17, 'Rug', 'Rug 2', 'livingRoom/rug2.jpg', '£40.00'),
(18, 'Rug', 'Rug 3', 'livingRoom/rug3.jpg', '£50.00'),
(19, 'Rug', 'Rug 4', 'livingRoom/rug4.jpg', '£90.00'),
(20, 'Rug', 'Rug 5', 'livingRoom/rug5.jpg', '£50.00'),
(21, 'Bookcases', 'Bookcase 1', 'livingRoom/bookcase1.jpg', '£400.00'),
(22, 'Bookcases', 'Bookcase 2', 'livingRoom/bookcase2.jpg', '£350.00'),
(23, 'Bookcases', 'Bookcase 3', 'livingRoom/bookcase3.jpg', '£400.00'),
(24, 'Bookcases', 'Corner Bookcase', 'livingRoom/bookcase4.jpg', '£350.00'),
(25, 'Bookcases', 'Thin Bookcase', 'livingRoom/bookcase5.jpg', '£400.00'),
(26, 'Media Units', 'Media Unit 1', 'livingRoom/mediaunit1.jpg', '£50.00'),
(27, 'Media Units', 'Media Unit 2', 'livingRoom/mediaunit2.jpg', '£40.00'),
(28, 'Media Units', 'Media Unit 3', 'livingRoom/mediaunit3.jpg', '£50.00'),
(29, 'Media Units', 'Media Unit 4', 'livingRoom/mediaunit4.jpg', '£40.00'),
(30, 'Media Units', 'Media Unit 5', 'livingRoom/mediaunit5.jpg', '£50.00'),
(31, 'Arm Chairs', 'Grey Arm Chair', 'livingRoom/greyArmChair.jpg', '£100.00'),
(32, 'Arm Chairs', 'Green Arm Chair', 'livingRoom/greenArmChair.jpg', '£100.00'),
(33, 'Arm Chairs', 'Yellow Arm Chair', 'livingRoom/yellowArmChair.jpg', '£100.00'),
(34, 'Arm Chairs', 'Teal Arm Chair', 'livingRoom/tealArmChair.jpg', '£100.00'),
(35, 'Arm Chairs', 'Eames Lounge Chair', 'livingRoom/eamesLoungeChair.jpg', '£3,000.00'),
(36, 'Lamps', 'USB Charging Lamp', 'livingRoom/usbLamp.jpg', '£100.00'),
(37, 'Lamps', 'Work Lamp', 'livingRoom/workLamp.jpg', '£80.00'),
(38, 'Lamps', 'Floor Lamp', 'livingRoom/floorLamp.jpg', '£40.00'),
(39, 'Lamps', 'Industrial Lamp', 'livingRoom/industrialLamp.jpg', '£100.00'),
(40, 'Lamps', 'Tripod Lamp', 'livingRoom/tripodLamp.jpg', '£50.00');